//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stmy.Quake.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stmy.Quake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   P    0.000 S    0.000   0      0
        ///P    0.416 S    0.703   0      2
        ///P    0.831 S    1.403   0      4
        ///P    1.243 S    2.099   0      6
        ///P    1.650 S    2.786   0      8
        ///P    2.052 S    3.465   0     10
        ///P    2.448 S    4.135   0     12
        ///P    2.838 S    4.794   0     14
        ///P    3.221 S    5.444   0     16
        ///P    3.600 S    6.084   0     18
        ///P    3.972 S    6.715   0     20
        ///P    4.340 S    7.338   0     22
        ///P    4.703 S    7.954   0     24
        ///P    5.062 S    8.564   0     26
        ///P    5.418 S    9.167   0     28
        ///P  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tjma2001 {
            get {
                return ResourceManager.GetString("Tjma2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///    4.800  2.844   0.0
        /// 4.950  2.931   0.5
        /// 5.090  3.012   1.0
        /// 5.220  3.088   1.5
        /// 5.340  3.157   2.0
        /// 5.450  3.221   2.5
        /// 5.550  3.278   3.0
        /// 5.640  3.329   3.5
        /// 5.720  3.375   4.0
        /// 5.780  3.409   4.5
        /// 5.820  3.431   5.0
        /// 5.840  3.441   5.5
        /// 5.860  3.451   6.0
        /// 5.880  3.461   6.5
        /// 5.900  3.471   7.0
        /// 5.920  3.481   7.5
        /// 5.940  3.491   8.0
        /// 5.960  3.501   8.5
        /// 5.980  3.511   9.0
        /// 6.000  3.521   9.5
        /// 6.020  3.531  10.0
        /// 6.040  3.541  10.5
        /// 6.060  3.552  11.0
        /// 6.080  3.562  11.5
        /// 6.100   [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Vjma2001 {
            get {
                return ResourceManager.GetString("Vjma2001", resourceCulture);
            }
        }
    }
}
